# Generated by Django 5.1.1 on 2024-10-07 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('text', models.TextField()),
                ('image', models.ImageField(default='shop/default.jpg', upload_to='aricles/')),
                ('counted_views', models.IntegerField(default=0)),
                ('rating', models.IntegerField(default=0)),
                ('pub_status', models.BinaryField(default=True)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('published_date', models.DateField(null=True)),
            ],
        ),
    ]
