# Generated by Django 5.1.1 on 2024-10-07 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='pub_status',
            field=models.BooleanField(default=True),
        ),
    ]
