# Generated by Django 5.1.1 on 2024-10-08 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_commentpost'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commentpost',
            old_name='product',
            new_name='post',
        ),
    ]
