# Generated by Django 5.1.1 on 2024-10-09 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_commentproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentproduct',
            name='rating',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
